// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AgentRequest struct {
	UserId  string `json:"userId"`
	Message string `json:"message"`
}

type AgentResponse struct {
	Intent string `json:"intent"`
	Reply  string `json:"reply"`
	Data   string `json:"data,optional"`
}
